version: '3.9'

services:
  postgres-reportes:
    image: postgres:14
    container_name: postgres-reportes
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: reportes_db
    ports:
      - "5432:5432"
    volumes:
      - reportes_pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  reportes_pgdata: